version: '3.8'

services:
  jsonprocessingapi:
    image: ${DOCKER_REGISTRY-}jsonprocessingapi
    build:
      context: .
      dockerfile: JsonProcessingApi/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - MongoDB__ConnectionString=mongodb://mongodb:27017
      - MongoDB__DatabaseName=JsonProcessingDB
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest

  messageconsumerapi:
    image: ${DOCKER_REGISTRY-}messageconsumerapi
    build:
      context: .
      dockerfile: MessageConsumerApi/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - rabbitmq
    environment:
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  mongodb_data: